# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84eac9617b312ffbda99100ee5783b6cc5060070fae824130ce24b7c1efa93b8baf5bf457812eeee564235a9f8c3f816635e199010ae571107b2a65e7195995b

test:
  secret_key_base: 82c111acf8cf3ce8e2beb3e8881c889f437558bfd958c6cd6ca1ab9ed237b1456fc64713d75dad01d2aa8e8c611b55ed4fe701e6bc8c20b0c41b8816c0bf44e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
